# Generated by Django 4.1.7 on 2023-03-09 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesingnationTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('empId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('active_field', models.BooleanField()),
                ('leave_count', models.IntegerField(default=0, null=True)),
                ('on_leave', models.BooleanField(default=False)),
                ('designation', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='project.desingnationtypes')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('active_field', models.BooleanField()),
                ('leave_count', models.IntegerField(default=0, null=True)),
                ('on_leave', models.BooleanField(default=False)),
                ('designation', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='project.desingnationtypes')),
            ],
        ),
    ]
